### PR TITLE
Mark this extension as parallel read-safe

### LINKED ISSUE #18: Why is this extension not parallel safe?
This extension to the best of my knowledge should be parallel safe and therefore must be marked as one so that we can use `-jauto` when generating docs.

### PR DESCRIPTION
**Pull request by thedrow**
Fixes #18.

### CODE REVIEW

**Review by doublethefish — APPROVED** [review]
It would be nice to have a deeper description in the commit message.

**Comment by doublethefish** [comment]
@alendit can you merge and release this to pip?

**Comment by thedrow** [comment]
> It would be nice to have a deeper description in the commit message.

Feel free to add one when merging this PR.

**Comment by thedrow** [comment]
Can we please merge and release?

**Pull request merged**
