### PR TITLE
added install_requires to setup.py, fixed Python 3 compatibility

### PR DESCRIPTION
**Pull request by greschd**

### CODE REVIEW

**Comment by alendit** [comment]
Thanks for your contribution. Is it ready to be merged?

**Comment by greschd** [comment]
Yes, it is.

**Comment by greschd** [comment]
Sorry, I had accidentally commited more after creating the pull request. I meant to go only up to commit cd3a8e00ed8fa21d76d2e4b2bce6

**Comment by greschd** [comment]
I'm not sure if you want the other changes -- they do two things:
* The module is given just by name now, not by path (this fixes an issue when the source file is not on the top level of the documentation source)
* The flags ``:classes:`` and ``:namespaces:`` determine which images are shown

Since this breaks backwards compatibility, I didn't mean to push those changes.

**Comment by alendit** [comment]
Hi,

the changes seem reasonable and there isn't much of existing usage, so I'll keep them.

Thanks.

**Pull request merged**
